version: "3"
services:
  webserver:
    depends_on:
      - api
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
  #    volumes:
  #      - /home/ubuntu/rstudio_docker/nginx.conf:/etc/nginx/nginx.conf
  #      - /home/ubuntu/ssl:/ssl/
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: unless-stopped
    #    volumes:
    #      - /c/data/database-data:/var/lib/postgresql/data/
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=pinapp
  web-app:
    depends_on:
      - api
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/apollo-subscriptions-example/node_modules
    ports:
      - "3000:3000"
    restart: on-failure
    container_name: web-app
    environment:
      - REACT_APP_API_URI=https://localhost:443/graphql
      - REACT_APP_WS_URI=wss://localhost:443/subscriptions
  api:
    depends_on:
      - postgres
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    restart: on-failure
    container_name: api
    volumes:
      - /app/apollo-subscriptions-example/node_modules # Inside the container, don't try to override this folder, just leave as is
    environment:
      #      - DEV_DATABASE_URL=postgres://<db_user>:<db_password>@localhost:5432/dev_db
      - HOST=localhost
      - PORT=3001
      - DB=pinapp
      - DBHOST=postgres
      - DBPORT=5432
      - DBUSER=postgres
      - DBPASSWORD=db_password
